### ISSUE TITLE
Initial ideas ...

### ISSUE THREAD

**Issue by amirhessam88** [slickml/slick-ml#1]
I started a TODO list which we need to take care of:

- Brainstorm for designing a logo for the org.
- test/ directory for the unittest.
- Add contribution guidelines to the `README file`.
- Add metrics example to the `README file`.
- Initialize the workflow to start writing the documentations.
- Initialize the folder for the paper based on the guideline at https://joss.theoj.org/.

Let me know your thoughts.
-Amir

**Comment by Tsmith5151** [comment]
Good initial thoughts. Also, need to look into updating the pypi package after successful builds. 

`deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "Your encrypted token"
`

**Comment by Tsmith5151** [comment]
Need to add how to get started and installation steps in the README

**Comment by amirhessam88** [comment]
> Need to add how to get started and installation steps in the README

**Comment by amirhessam88** [comment]
- For the Installation part, we need to add required links for virtual env and anaconda as well so it will reduce any confusion for the user.

**Comment by amirhessam88** [comment]
Closing this, we almost did everything + have separate issues for remaining ...
