### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by amirhessam88** [slickml/slick-ml#21]
I have put together **5** variations of **2** logos among the ones I sent y'all before.
Let's vote to go with one for now. We can change it later.

# 1. logo1.png
![logo1](https://user-images.githubusercontent.com/18218820/92299308-e051d600-ef16-11ea-8303-48f90c0b40de.png)
# 2. logo2.png
![logo2](https://user-images.githubusercontent.com/18218820/92299309-e0ea6c80-ef16-11ea-86b6-2727ea977ce4.png)
# 3. logo3.png
![logo3](https://user-images.githubusercontent.com/18218820/92299310-e0ea6c80-ef16-11ea-985c-357873cc8d5b.png)
# 4. logo4.png
![logo4](https://user-images.githubusercontent.com/18218820/92299311-e1830300-ef16-11ea-82ef-ddc538c584a6.png)
# 5. logo5.png
![logo5](https://user-images.githubusercontent.com/18218820/92299312-e1830300-ef16-11ea-9f53-ba4b4d1c1962.png)
# 6. logo6.png
![logo6](https://user-images.githubusercontent.com/18218820/92547487-96b90200-f21a-11ea-9f35-597010f3aa2f.png)
# 7. logo7.png
![logo7](https://user-images.githubusercontent.com/18218820/92547460-8acd4000-f21a-11ea-80a8-27c8b67565d9.png)

**Comment by Tsmith5151** [comment]
Like the color scheme for #5. @amirhessam88 @eitanlees  thoughts?

**Comment by eitanlees** [comment]
I vote for number two

**Comment by amirhessam88** [comment]
haha. What should we do ? :D

**Comment by eitanlees** [comment]
I think legibility is important. 3-5 are confusing and 1 is no good.

**Comment by amirhessam88** [comment]
I did get some votes from other people. Here are the comments:
- Color of 1 and 2 are close to the logo of Slack.
- 3-5 is cool since they pattern of "S" is built by repeating the same pattern twice.
My personal opinion is still 3.
Let's wrap up the final decision this week.

**Comment by Tsmith5151** [comment]
I could go with #3 too. Can we try different color schemes for #2?

**Comment by amirhessam88** [comment]
I will try new color scheme for the #2

**Comment by amirhessam88** [comment]
Added Two more logos (#6 and #7) on the top.

**Comment by Tsmith5151** [comment]
Starting to like #6...any seconds?

**Comment by Tsmith5151** [comment]
Or #7 without the circles in the center.

**Comment by amirhessam88** [comment]
#7 without the circles is #6.

**Comment by amirhessam88** [comment]
So, I am gonna add #6 for now. Then, we change it later at any point soon.

**Comment by Tsmith5151** [comment]
Can we close this now? Are we all in agreement on the logo?

**Comment by amirhessam88** [comment]
sure
*Amirhessam Tahmassebi, Ph.D.*

*www.amirhessam.com*  <http://www.amirhessam.com>
