### ISSUE TITLE
Separate Plotting Routines

### ISSUE THREAD

**Issue by eitanlees** [slickml/slick-ml#3]
Amir and I discussed creating a separate `plotting.py` file to handle various plotting routines. 

I will track the progress in this issue.

**Comment by amirhessam88** [comment]
@eitanlees Just crated the `plotting.py`.
I did separate the plot_binary_classification_metrics from `metrics.py`.
The function for plotting, receive the dict_object created by the class as **kwargs**
So, the object from BinaryClassificationMetrics class has now the ability of **.plot()** 
Please let me know your thoughts. So, we can revise it if needed.

**Comment by amirhessam88** [comment]
Solved.
