### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by amirhessam88** [slickml/slick-ml#32]
Here we can brainstorm the option for writing the documentations and API details. I have seen mostly use `readthedocs` and `Sphinx`.
Any other options ?

**Comment by amirhessam88** [comment]
I think we need to have slickml.github.io blog for all the documentations and walk-through. any thoughts ?

**Comment by amirhessam88** [comment]
We can also use this https://pages.github.com/
idk which one is better, but sooner or later we need to start writing the documentations. Since, the package is getting bigger.

**Comment by Tsmith5151** [comment]
Agree on using Sphinx to build the docs and tutorials. For readthedocs, a webhook configured with the project repo and automatically run a new build to re-generate the updated docs on each merged PR. Also, minimal steps to have the docs published.

**Comment by amirhessam88** [comment]
Awesome. Please start the doc part. As we discussed we can do something similar to `SHAP` docs.

**Comment by amirhessam88** [comment]
Addresed in https://github.com/slickml/slick-ml/pull/77
