### ISSUE TITLE
Bug in Metrics DataFrame

### ISSUE THREAD

**Issue by Tsmith5151** [slickml/slick-ml#65]
When styling the output metrics dataframe, the following error can be thrown due to threshold rounding. 

```
display(df_to_show.style.background_gradient(cmap = cm).set_table_styles(styles))
```

```
ValueError: style is not supported for non-unique indices.
```

@amirhessam88, this appears to be a rounding issue when naming the dataframe index and changing to `4f` should resolve the duplicate indices names. 

```
metrics_df = pd.DataFrame(
            data=self.metrics_dict_,
            index=[
                f"""Threshold = {self.threshold:.3f} | Average =
                {self.average_method.title()}"""
            ],
        )
```

**Comment by amirhessam88** [comment]
Just fixed it. It is now follow `precision_digits` that you can call in the class.
