### ISSUE TITLE
Switching over to Poetry for Dependency Management

### ISSUE THREAD

**Issue by Tsmith5151** [slickml/slick-ml#72]
Recommend switching over to [poetry](https://python-poetry.org/) to help handling versioning issues. Also, poetry allows automated versioning which is helpful when updating the package on PyPi. Integration with PyPi is pretty seamless, which is an added plus.

**Comment by amirhessam88** [comment]
We need to make sure we have the `setup.py` is working with it since the PyPI is linked to that.

**Comment by amirhessam88** [comment]
Addresed in https://github.com/slickml/slick-ml/pull/77
