### ISSUE TITLE
Switch over to GitHub Actions

### ISSUE THREAD

**Issue by Tsmith5151** [slickml/slick-ml#73]
Recommend using GitHub Actions and workflow for CI/CD automation testing. Currently using travis.ci, but with GitHub workflows, we will have all the jobs/logs centralized in one place.

**Comment by amirhessam88** [comment]
@Tsmith5151 Great idea. Just updated all of the `requirements.txt`. I think we can stabilize the current version where all of the versions are the latest in terms of CI/CD and GitHub Actions and retire Travis CI.

**Comment by amirhessam88** [comment]
Addresed in https://github.com/slickml/slick-ml/pull/77
