### ISSUE TITLE
[FEATURE]: Endpoint of the generated API Doc via Sphinx

### ISSUE THREAD

**Issue by amirhessam88** [slickml/slick-ml#81]
### Describe the feature you are interested in ...

Currently, we do have the workflow to generate the API doc by running `poe sphinx`. However, we do not have the endpoint to present it. We do have host/domain at https://www.slickml.com to be used as the end point. Another option would be https://readthedocs.org/.
Would like to know your thoughts and other options ?

**Comment by chadac** [comment]
Is there any planned functional infrastructure for the website? Simplest approach would be to have it as a subfolder on the existing (I assume) static website, or set up a separate subdomain with a cloned static website subset if you're wanting to self-host. We'd also probably want something to notify us if the website goes down. Readthedocs is quite a bit simpler and technically is a lot less to manually manage.

I'd go with Readthedocs personally.

**Comment by Tsmith5151** [comment]
Agree, it would be a lot easier to use Readthedocs to host the sphinx documentation. [GitBook](https://www.gitbook.com/?utm_source=content&utm_medium=trademark&utm_campaign=jHFZrYjcqPtz37l0Jx0B) is also another option, which allows custom domains.

**Comment by amirhessam88** [comment]
sounds good to me

**Comment by amirhessam88** [comment]
@chadac @Tsmith5151 Just added the endpoint + automatic deployment of the API docs to https://www.docs.slickml.com in https://github.com/slickml/slick-ml/pull/104

I am still down for a fancier/better option; at least we have an automatic deployment of the website now.

**Comment by amirhessam88** [comment]
+ https://github.com/slickml/slick-ml/issues/125

**Comment by amirhessam88** [comment]
https://github.com/slickml/slick-ml/pull/127
